### ISSUE TITLE
Setup failed

### ISSUE THREAD

**Issue by ray-bun** [dan-v/awslambdaproxy#12]
-sh-4.2$ ./awslambdaproxy setup
Failed to run setup for awslambdaproxy: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors-sh-4.2$ ^C

**Comment by dan-v** [comment]
@mrWiga - you need to make sure your AWS credentials are available - what method are you using to provide credentials? see step 3 in the readme (https://github.com/dan-v/awslambdaproxy#usage).

**Comment by ray-bun** [comment]
Thanks Dan. Got it!
