### ISSUE TITLE
2020/04/25 06:36:41 tunnelconnection.go:226: Waiting for tunnel to be established..

### ISSUE THREAD

**Issue by ray-bun** [dan-v/awslambdaproxy#13]
I'm trying to run during startup. What does this mean?

2020/04/25 06:36:05 gost.go:657: auto://:8080 on [::]:8080
2020/04/25 06:36:06 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:07 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:08 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:09 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:10 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:11 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:12 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:13 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:14 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:15 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:16 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:17 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:18 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:19 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:20 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:21 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:22 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:23 tunnelconnection.go:226: Waiting for tunnel to be established..
2020/04/25 06:36:24 tunnelconnection.go:226: Waiting for tunnel to be established..

**Comment by dan-v** [comment]
Read step 1 from readme: https://github.com/dan-v/awslambdaproxy#usage. You need to open those ports or tunnel won't be established.

**Comment by ray-bun** [comment]
But it's working if I don;t run it from /etc/rc.local.

**Comment by ray-bun** [comment]
in /etc/rc.local I have
/home/ec2-user/Main_Run_Proxy.sh > /home/ec2-user/main_run.log 2>&1 &

Main_Run_proxy.sh
#!/bin/bash
export AWS_ACCESS_KEY_ID=**
export AWS_SECRET_ACCESS_KEY=**
/home/ec2-user/awslambdaproxy/build/linux/x86-64/awslambdaproxy setup
/home/ec2-user/awslambdaproxy/build/linux/x86-64/awslambdaproxy run -r ap-southeast-2,ap-southeast-2

**Comment by dan-v** [comment]
@mrWiga - the way it works is the ssh authorized_keys file for the _current_ user is updated to allow reverse tunnels from Lambda functions. The current user will differ in the case of running it under rc.local (root) as opposed to running it manually as the default ec2-user. By default the root user is generally not permitted to login over ssh, and I definitely wouldn't recommend changing that.

I'd highly recommend not running it in rc.local, as that is not meant to be a process supervisor. I don't have a example handy, but take a look at systemd instead. There's also a docker image for this now that simplifies the process supervision, but I haven't documented how to use it yet.
