### ISSUE TITLE
error closing connection message on v0.0.13

### ISSUE THREAD

**Issue by dan-v** [dan-v/awslambdaproxy#16]
This error has always been occurring, but it just happens to be logged now:
`error closing connection for connectionID=127.0.0.1:47858: close tcp 127.0.0.1:8081->127.0.0.1:47858: use of closed network connection`

**Comment by yurymkomarov** [comment]
Hello @dan-v,
What is the issue case?

**Comment by mlitwiniuk** [comment]
@yurymkomarov It seems that when something is using connection that is about to be closed, app fails to close if even after a while and everything gets stale.

**Comment by yurymkomarov** [comment]
@mlitwiniuk I see, thanks )

**Comment by rjay98** [comment]
This happens to me as well @yurymkomarov !

**Comment by russian-developer** [comment]
and me.
