### ISSUE TITLE
Different Ip for each request ?

### ISSUE THREAD

**Issue by NotMoni** [dan-v/awslambdaproxy#18]
Hey, can we have a different IP for each request?

**Comment by dan-v** [comment]
Hi @NotMoni - unfortunately not possible. The current design opens a reverse SSH tunnel from a single Lambda function at a time, so the closest you could get is to just set the rotation to happen as frequently as possible. In theory, it should be possible to make code changes here to open multiple tunnels at once and round robin requests among those tunnels.
