### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by russian-developer** [dan-v/awslambdaproxy#20]
### Prerequisites

* [ yes ] I am running the [latest version](https://github.com/dan-v/awslambdaproxy/releases) of awslambdaproxy
* [ yes ] I am have read the [README](https://github.com/dan-v/awslambdaproxy#usage) instructions and the [FAQ](https://github.com/dan-v/awslambdaproxy#faq)

### Description

I sent recursive 100 parallel requests and got panic error in 10 seconds.

### Steps to Reproduce

1. Download or compile the awesome software
2. Run it (I used the next keys `./awslambdaproxy run -r us-west-2,us-west-1,us-east-1,us-east-2 -l "cL3Rjea6E:uQ06OWgdr@:8080" -m 512 -f 10m --debug`)
3. Run 100 recursive, parallel requests
4. Wait up to 10 seconds

**Expected behavior:** [What you expected to happen]

I expect, that awslmbdaproxy will work

**Actual behavior:** [What actually happened]

I got panic error

### Environment

awslambdaproxy 0.0.13 and 0.0.14
Linux service 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

### Error Output

Error log is too big. I've attached it.
[awslambdaproxy.log](https://github.com/dan-v/awslambdaproxy/files/5558935/awslambdaproxy.log)

**Comment by russian-developer** [comment]
Easy way to reproduce
```
$ hey -n 5000 -c 200  -x 'http://admin:awslambdaproxy@<PROXY_IP_HERE>:8080' https://github.com/
```

I found that number of connections with port 8082 is growing up during the test.
from 32 at startup to 1600 at the panic error

**Comment by dan-v** [comment]
Hi @unk2k - thanks for reporting this issue. This project was created just as a small prototype and definitely not designed to be used a high performance proxy with a large number of connections. There's a lot of work to refactor this into a real production quality solution, and that is not something I currently intend on doing, but maybe at some point in the future. Be aware that there is likely a hard limit on the number of outbound connections allowed from a single Lambda function (not sure what that is off the top of my head), so I would assume you'd be bumping into that here. The specific fatal log you posted looks like a concurrency bug (and there's probably a number of them in this current codebase). Happy to take any PRs to fix that.

**Comment by russian-developer** [comment]
@dan-v You were right. There is a limit in 1024 file descriptors. which means that the error should be around it. I'll come back if I found something.
