### ISSUE TITLE
Can we open multiple connections in the same region?

### ISSUE THREAD

**Issue by bryank91** [dan-v/awslambdaproxy#22]
**Describe the solution you'd like**
I want to have a single PC but running multiple tasks with different IP addresses.
In this case, I will connect to lambda functions and all the request maintains the same IP until after a certain amount of time. 

**Describe alternatives you've considered**
Perhaps running ./awslambdaproxy multiple times? However, it will still go through the ec2 instance.

**Comment by lezwon** [comment]
Would like to have this. @dan-v is this possible?

**Comment by dan-v** [comment]
@bryank91 - the general idea of running multiple instances of the proxy from a single ec2 instance _should_ be possible, but currently there are some things that are hardcoded like some listening ports (e.g https://github.com/dan-v/awslambdaproxy/blob/fcada1d421a72a92525a4ea17c2aeb365141c4bc/pkg/server/localproxy.go#L12) that would prevent this from working. i'm happy to take any PRs to make values like these configurable so this workflow could work..
