### ISSUE TITLE
Maximising diversity but with reliable startup

### ISSUE THREAD

**Issue by GrahamCobb** [dan-v/awslambdaproxy#23]
Hi, Thanks very much for this, which is pretty much exactly what I was looking for.

I am trying to reliably run lambda proxies with as much diversity as possible. However, I find that with a fairly long list of regions there is always one or more regions which fail to start (not always the same ones). If one fails, the whole startup fails.

It would be really great if there was an option to ignore any errors, as long as at least one region had started. Ideally with a clear and unambiguous summary of which were set up once the startup has completed.

I have tried dropping the least reliable regions but the list of regions which have never failed to start is getting quite short now :-(

Of course, a dynamic approach, with attempts to restart failed regions and tolerate all errors as long as at least one proxy is usable, would be ideal but it isn't needed for my use case, at least. I tend to run the service for a day or so and am more concerned about reliable startup, as diversely as possible, than with long term usage.

**Comment by dan-v** [comment]
hi @GrahamCobb - i'm going to close this out, but if you are still using this feel free to open two issues using the github templates. 1) bug report for startup failures and include all the requested data there 2) feature request to tolerate errors as long as one region is working.
