### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by mayank2567** [dan-v/awslambdaproxy#6]
What is the username and the password that the proxy server asks for after setting up everything?

**Comment by dan-v** [comment]
> awslambdaproxy run -h
This will execute awslambdaproxy in regions specified. Examples:
...
Example 2 - Choose a different port and username/password for proxy and add another listener on localhost with no auth
./awslambdaproxy run -r us-west-2 -l "admin:admin@:8888,localhost:9090"

**Comment by mrWiga** [comment]
How do I change username/password for security?
