### ISSUE TITLE
Can I use an EC2 IAM attached role?

### ISSUE THREAD

**Issue by nodesocket** [dan-v/awslambdaproxy#7]
When I run:

```
awslambdaproxy run us-west-1,us-west-2,us-east-1,us-east-2
```

Getting:

```
Must specify environment variable AWS_ACCESS_KEY_ID
```

The EC2 instance should already have the policies needed via the attachd IAM role.

**Comment by dan-v** [comment]
Hey @nodesocket. It can run with an IAM profile, but there is a check preventing it from running currently: https://github.com/dan-v/awslambdaproxy/blob/master/cmd/awslambdaproxy/cmd/run.go#L70. With that removed it should work fine.

I haven't updated this project in quite a while and it needs a little love. Building from source appears to be problematic at the moment (needs to move to go modules and go-bindata appears to have been abandoned). I'll leave this issue open and try to fix it and the build process when I get a chance. Also open to any PRs.

**Comment by dan-v** [comment]
Pushed new release that removes this hardcoded environment variable check.
